### ISSUE TITLE
[Windows] Installer does not create desktop icon

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#158]
As reported in the forums, the installer does not create desktop icon for some users.

**Comment by josegomez** [comment]
This should work, it is handled here
https://github.com/sqrldev/SQRLDotNetClient/blob/f1c5dc0ac3040e1f4c9b3f091c941962641fd645/SQRLPlatformAwareInstaller/ViewModels/VersionSelectorViewModel.cs#L439-L462

I am not sure what could case it to not work, we probably need to add more logging.

**Comment by alexhauser** [comment]
Hmmm... only thing that quickly comes to mind is that maybe the PowerShell security model (aka `ExecutionPolicy`) kicks in. But that should usually only happen for scripts downloaded from the internet afaik. 

So yeah, we'll need some logging there for sure.

**Comment by dxcSithLord** [comment]
This may (or may not help).  First test for SQRLDotNetClientUI - install, launch and create new ID.  This failed with a crash (yes I know this looks like a new issue).  As I have installed dotNet, I launched using
`dotnet SQRLDotNetCLientUI.dll` with the same result, but I received some logging (See below).  This appears to be missing the libsodium, which if you are using powershell - ANY UNSIGNED SCRIPT, will fail on the execution policy.  This is a "new built" Windows 10 Home edition, using the latest release version. 

PS C:\Program Files\SQRL> dotnet .\SQRLDotNetClientUI.dll
[18:54:53 INF] New app instance is being launched on Microsoft Windows 10.0.18363
[18:54:53 INF] DB Directory: C:\Program Files\SQRL
C:\Program Files\SQRL: True
[18:54:54 INF] IPC server starts listening...
[18:54:55 INF] DB Directory: C:\Program Files\SQRL
C:\Program Files\SQRL: True
[18:54:55 INF] DB Directory: C:\Program Files\SQRL
C:\Program Files\SQRL: True
[18:54:55 INF] IdentityManager initialized.
[18:54:55 INF] App initialization completed!
[18:54:55 INF] NotifyIcon implementation available, setting up NotifyIcon
[18:54:55 INF] Registering to receive session notifications
[18:54:55 INF] SystemEventNotifier polling task started
[18:54:55 INF] QuickPass system event handlers initialized.
[18:54:55 INF] QuickPassManager initialized.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Sodium.SodiumCore' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libsodium' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Sodium.SodiumLibrary.sodium_init()
   at Sodium.SodiumCore.Init()
   at Sodium.SodiumCore..cctor()
   --- End of inner exception stack trace ---
   at Sodium.SodiumCore.Init()
   at SQRLUtilsLib.SQRL.CreateRescueCode()
   at SQRLDotNetClientUI.ViewModels.NewIdentityViewModel..ctor()
   at SQRLDotNetClientUI.ViewModels.MainMenuViewModel.OnNewIdentityClick()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Avalonia.Data.Converters.AlwaysEnabledDelegateCommand.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_9(InputElement x, PointerReleasedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SQRLDotNetClientUI.Program.Main(String[] args)
[18:55:01 INF] App shutting down
[18:55:01 INF] Attempting to End CPS Gracefully from Process Exit Event
[18:55:01 ERR] Failed to Cancel CPS Gracefully
[18:55:01 INF] Forcing exit because of IPC thread still running.
[18:55:01 INF] Attempting to End CPS Gracefully from Process Exit Event
[18:55:01 ERR] Failed to Cancel CPS Gracefully
PS C:\Program Files\SQRL>

**Comment by dxcSithLord** [comment]
Same problem if I re-install as administrator and run as administrator, using 
`PS C:\Program Files\SQRL> dotnet .\SQRLDotNetClientUI.dll`
Install log attached
[SQRLInstallerLog20200508.log](https://github.com/sqrldev/SQRLDotNetClient/files/4600814/SQRLInstallerLog20200508.log)
SQRLPlatformAwareInstaller version 0.1.2.0

**Comment by dxcSithLord** [comment]
I downloaded the (current) master and ran `dotnet build`.  Using the built installer, with execution policy set to Restricted, no desktop shortcut.  Re-ran with execution policy set to unrestricted and desktop shortcut exists.  Installer ran with elevated privileges.  I was hoping the problems were related, but perhaps not.

**Comment by josegomez** [comment]
@dxcSithLord are you using the installer to install this? 

> This may (or may not help). First test for SQRLDotNetClientUI - install, launch and create new ID. This failed with a crash (yes I know this looks like a new issue). As I have installed dotNet, I launched using
> `dotnet SQRLDotNetCLientUI.dll` with the same result, but I received some logging (See below). This appears to be missing the libsodium, which if you are using powershell - ANY UNSIGNED SCRIPT, will fail on the execution policy. This is a "new built" Windows 10 Home edition, using the latest release version.
> 
> PS C:\Program Files\SQRL> dotnet .\SQRLDotNetClientUI.dll
> [18:54:53 INF] New app instance is being launched on Microsoft Windows 10.0.18363
> [18:54:53 INF] DB Directory: C:\Program Files\SQRL
> C:\Program Files\SQRL: True
> [18:54:54 INF] IPC server starts listening...
> [18:54:55 INF] DB Directory: C:\Program Files\SQRL
> C:\Program Files\SQRL: True
> [18:54:55 INF] DB Directory: C:\Program Files\SQRL
> C:\Program Files\SQRL: True
> [18:54:55 INF] IdentityManager initialized.
> [18:54:55 INF] App initialization completed!
> [18:54:55 INF] NotifyIcon implementation available, setting up NotifyIcon
> [18:54:55 INF] Registering to receive session notifications
> [18:54:55 INF] SystemEventNotifier polling task started
> [18:54:55 INF] QuickPass system event handlers initialized.
> [18:54:55 INF] QuickPassManager initialized.
> Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> ---> System.TypeInitializationException: The type initializer for 'Sodium.SodiumCore' threw an exception.
> ---> System.DllNotFoundException: Unable to load DLL 'libsodium' or one of its dependencies: The specified module could not be found. (0x8007007E)
> at Sodium.SodiumLibrary.sodium_init()
> at Sodium.SodiumCore.Init()
> at Sodium.SodiumCore..cctor()
> --- End of inner exception stack trace ---
> at Sodium.SodiumCore.Init()
> at SQRLUtilsLib.SQRL.CreateRescueCode()
> at SQRLDotNetClientUI.ViewModels.NewIdentityViewModel..ctor()
> at SQRLDotNetClientUI.ViewModels.MainMenuViewModel.OnNewIdentityClick()
> --- End of inner exception stack trace ---
> at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
> at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> at System.Delegate.DynamicInvokeImpl(Object[] args)
> at System.Delegate.DynamicInvoke(Object[] args)
> at Avalonia.Data.Converters.AlwaysEnabledDelegateCommand.Execute(Object parameter)
> at Avalonia.Controls.Button.OnClick()
> at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
> at Avalonia.Input.InputElement.<>c.<.cctor>b__25_9(InputElement x, PointerReleasedEventArgs e)
> at System.Reactive.AnonymousObserver`1.OnNextCore(T value) at System.Reactive.ObserverBase`1.OnNext(T value)
> at System.Reactive.Subjects.Subject`1.OnNext(T value) at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
> at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target) at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
> at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
> at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
> at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
> at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
> at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e)
> at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
> at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
> at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
> at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
> at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
> at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
> at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
> at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
> at SQRLDotNetClientUI.Program.Main(String[] args)
> [18:55:01 INF] App shutting down
> [18:55:01 INF] Attempting to End CPS Gracefully from Process Exit Event
> [18:55:01 ERR] Failed to Cancel CPS Gracefully
> [18:55:01 INF] Forcing exit because of IPC thread still running.
> [18:55:01 INF] Attempting to End CPS Gracefully from Process Exit Event
> [18:55:01 ERR] Failed to Cancel CPS Gracefully
> PS C:\Program Files\SQRL>

I'm a little confused as to how you got here, you installed using the installer and then it immediately crashed when you launched it complaining about libsodium? Is that' what I'm understanding here?

**Comment by dxcSithLord** [comment]
Here is a PSR recording attached - they show what I did - the logs show what happened in the background.
[SQRLCLient_Test_1_New_Id_Fail.zip](https://github.com/sqrldev/SQRLDotNetClient/files/4601089/SQRLCLient_Test_1_New_Id_Fail.zip)
[SQRLCLient_Test_2_Help_and_New_Id_Fail.zip](https://github.com/sqrldev/SQRLDotNetClient/files/4601090/SQRLCLient_Test_2_Help_and_New_Id_Fail.zip)

**Comment by dxcSithLord** [comment]
Perhaps not using powershell to create the shortcut (see ref [https://stackoverflow.com/questions/4897655/create-a-shortcut-on-desktop](https://stackoverflow.com/questions/4897655/create-a-shortcut-on-desktop) ) may be an option?
I was hoping that the two problems were related.

**Comment by josegomez** [comment]
Wonderful thank you @dxcSithLord this looks like a new issue so I'm opening a new one

**Comment by josegomez** [comment]
> Perhaps not using powershell to create the shortcut (see ref https://stackoverflow.com/questions/4897655/create-a-shortcut-on-desktop ) may be an option?
> I was hoping that the two problems were related.

Gets tricky with .netcore can't bring along any windows specific references without other issues. That's why we opted to go external (powershell)
I'll poke about some more
