### ISSUE TITLE
Detect VC++ Runtime (missing)

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#175]
This may (or may not help).  First test for SQRLDotNetClientUI - install, launch and create new ID.  This failed with a crash (yes I know this looks like a new issue).  As I have installed dotNet, I launched using
`dotnet SQRLDotNetCLientUI.dll` with the same result, but I received some logging (See below).  This appears to be missing the libsodium, which if you are using powershell - ANY UNSIGNED SCRIPT, will fail on the execution policy.  This is a "new built" Windows 10 Home edition, using the latest release version. 
<details>
<summary> Log </summary>
PS C:\Program Files\SQRL> dotnet .\SQRLDotNetClientUI.dll
[18:54:53 INF] New app instance is being launched on Microsoft Windows 10.0.18363
[18:54:53 INF] DB Directory: C:\Program Files\SQRL
C:\Program Files\SQRL: True
[18:54:54 INF] IPC server starts listening...
[18:54:55 INF] DB Directory: C:\Program Files\SQRL
C:\Program Files\SQRL: True
[18:54:55 INF] DB Directory: C:\Program Files\SQRL
C:\Program Files\SQRL: True
[18:54:55 INF] IdentityManager initialized.
[18:54:55 INF] App initialization completed!
[18:54:55 INF] NotifyIcon implementation available, setting up NotifyIcon
[18:54:55 INF] Registering to receive session notifications
[18:54:55 INF] SystemEventNotifier polling task started
[18:54:55 INF] QuickPass system event handlers initialized.
[18:54:55 INF] QuickPassManager initialized.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Sodium.SodiumCore' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libsodium' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Sodium.SodiumLibrary.sodium_init()
   at Sodium.SodiumCore.Init()
   at Sodium.SodiumCore..cctor()
   --- End of inner exception stack trace ---
   at Sodium.SodiumCore.Init()
   at SQRLUtilsLib.SQRL.CreateRescueCode()
   at SQRLDotNetClientUI.ViewModels.NewIdentityViewModel..ctor()
   at SQRLDotNetClientUI.ViewModels.MainMenuViewModel.OnNewIdentityClick()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Avalonia.Data.Converters.AlwaysEnabledDelegateCommand.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_9(InputElement x, PointerReleasedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SQRLDotNetClientUI.Program.Main(String[] args)
[18:55:01 INF] App shutting down
[18:55:01 INF] Attempting to End CPS Gracefully from Process Exit Event
[18:55:01 ERR] Failed to Cancel CPS Gracefully
[18:55:01 INF] Forcing exit because of IPC thread still running.
[18:55:01 INF] Attempting to End CPS Gracefully from Process Exit Event
[18:55:01 ERR] Failed to Cancel CPS Gracefully
PS C:\Program Files\SQRL>
</details>

After investigating further, this is due to a missing VC++ Runtime Exception so I've changed the issue to notate that. We will need to either bring it along with us or notify that it is missing.

.

_Originally posted by @dxcSithLord in https://github.com/sqrldev/SQRLDotNetClient/issues/158#issuecomment-625945098_

**Comment by josegomez** [comment]
See Recordings here 
https://github.com/sqrldev/SQRLDotNetClient/issues/158#issuecomment-625971259

**Comment by josegomez** [comment]
@dxcSithLord found the issue, for LibSodium to work on windows you need VC++ Runtime.
This little guy
https://www.microsoft.com/en-us/download/details.aspx?id=48145
If you download and run that then the program works as expected (shortcut issue aside)

**Comment by josegomez** [comment]
Looks like we should check the following Keys

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x86
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\X64
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x86
```

**Comment by dxcSithLord** [comment]
I have restored the machine, back to a baseline (never before seen SQRL).
I ran the installer as administrator and the desktop icon appears (FYI), but I have confirmed the keys:
Get-ChildItem hklm:softwaRE\microsoft\ | findstr /I "visual"
                               VisualizationsDir         : C:\Program Files\Windows Media Player\Visualizations
Get-ChildItem hklm:softwaRE\wow6432Node\microsoft\ | findstr /I "visual"
                               VisualizationsDir         : C:\Program Files\Windows Media Player\Visualizations
PS C:\Windows\system32>

So no VisualStudio runtime here.

**Comment by josegomez** [comment]
great @dxcSithLord now see if New Identity button works (it shouldn't) then install the VC runtime and that should fix it.

**Comment by dxcSithLord** [comment]
I have installed vc_uwpdesktop.140.exe from [https://www.microsoft.com/en-us/download/details.aspx?id=53175](https://www.microsoft.com/en-us/download/details.aspx?id=53175), but fails.  The instructions for VS14.0 suggest that the following is required there is a reference to be applied to the app.  
I also tried with VC_redist.x64.exe, which appears to be the latest and after installing that, the SQRLDotNetClientUI did NOT crash and I have successfully created a new identity.

**Comment by josegomez** [comment]
@dxcSithLord I provided the link above what you need is the VC++ redistributable (the second one you installed) not sure where vc_uwpdesktop came from.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

But thanks for confirming that fixes the issue.

**Comment by alexhauser** [comment]
> Looks like we should check the following Keys
> 
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x86
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64
> HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\X64
> HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x86
> ```

Working on this right now, @josegomez!
I dont't think we need to check the 32bit stuff though, do we?

**Comment by josegomez** [comment]
Well if there’s someone running 32 bits maybe? If it isn’t a ton of effort I’d say we check it but up to you

**Comment by alexhauser** [comment]
Are we even offering x86 releases, @josegomez? 
All our assets end in `_x64`.

I'm looking into quietly installing the vc++ redistributable runtime if it isn't there already, and and if we only have x64 binaries anyway, that would reduce the effort both for checking and installing the right version.

**Comment by josegomez** [comment]
Sounds good!

**Comment by dxcSithLord** [comment]
I compiled this on Raspberrypi - that 32bit operating system called Raspbian (a clone of Debian), and i had the same problem.  Crash on new id.  Haven't yet found download link to install visualstudio runtime for linux ARM 32bit.  Note this edge case has more than 12million potential installations (last time I saw the number of Raspberry Pi sales figures advertised).

**Comment by alexhauser** [comment]
@dxcSithLord, I doubt that the VC++ runtime is involved in the build of libsodium for Debian/Raspbian. Are you sure that libsodium is installed at all?

**Comment by josegomez** [comment]
@dxcSithLord there is no vc for raspberry but you shouldn’t need it 
I’m guessing what you need for it is gcc and lib c and lib sodium for pi

**Comment by dxcSithLord** [comment]
I thought that the lib sodium was part of the install?  Anyway, simple fix :
sudo apt update
sudo apt install libsodium-dev 
(Note that sudo elevates privilege and is required for package management)

If this is already installed the package management handles that - returns success if at the end it is installed.  
Let me know if you want to test for existence, or result of this command and I can provide bash script for you.
SQRLDottNetUI runs and that problem resolved.  Please add to linux install (apt will handle 32 or 64bit)
If this project can be made into an apt or rpm package, this is how most things in linux get installed.  Your installer would be pulled by the package install, then run (GUI/nonGUI install).

**Comment by josegomez** [comment]
Awesome @dxcSithLord 
Yes lib sodium is included for Linux but only x86 not arm
